### ISSUE TITLE
ARM64 compatibility

### ISSUE THREAD

**Issue by irineu** [Soreing/rsa-cpp-encrypt#1]
Hi, i'm trying to build for ARM64 processor, but i'm getting some errors with ASM code:

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/978586/229583017-f6c7b106-1fe2-47e7-a5f5-1cc47d85f0ee.png">

**Comment by Soreing** [comment]
The underlying big integer library is only implemented for x86 architecture.
There are no plans to support ARM anytime soon.
